[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short -p no:randomly --order-scope=module
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
markers =
    smoke: 冒烟测试
    system: 系统测试
    core: 核心测试
